### ISSUE TITLE
Wrong numbers

### ISSUE THREAD

**Issue by Milaine** [pigpagnet/save-your-telegram-history#17]
"57520 messages out of 10400 (553%). Time 1.135 sec."
I just wanted to tell you because I really want you guys to succeed, I'm very very glad I can finally archive my chat.
Good job until now and I'm hyped for images/media.
I'm hoping bugreporting helps you a little

**Comment by vanchope** [comment]
Thanks for reporting the bug. Regarding images/media, we have released a partial support for images in the new version (2.1.0).

**Comment by taikamiya** [comment]
Bug persists in 2.1.0 - I believe I got it clicking various higher load options over (eg clicking 50k, then 20k), but I'm not sure. The log reflected this by showing redundant segments of logs (eg I'd have the same 20k lines repeated over and over). There's probably a more graceful method, but reinstalling and just loading "all" worked for me

**Comment by vanchope** [comment]
We have just released in version 2.2.2. a fix for a problem #35. The problem led to freezing and adding redundant segments of logs (and, as a consequence, wrong numbers) after repeatedly clicking the button of the extension. @taikamiya @Milaine could you please check whether the issue still persists?
